### ISSUE TITLE
Handling case in custom and random URLs

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/drupal_yourls#8]
We talked about case in the presentation meeting. 

Proposal
- Case insensitive for the custom URLs (`Apply`, `apply`, `APPLY`, etc. are considered the same)
- Random are case sensitive to increase the number of possibilities with a small number of characters

**Comment by brookestevens** [comment]
Added this plugin to the YOURLS install to make custom short links case insensitive [yourls-case-insensitive](https://github.com/adigitalife/yourls-case-insensitive). This also allows random urls to contain both upper and lower case letters.
